### ISSUE TITLE
Fix terms of use

### ISSUE THREAD

**Issue by manujuniris** [archethic-foundation/archethic-website#75]
**Problem -** 

![Screenshot from 2022-06-10 14-15-42](https://user-images.githubusercontent.com/90322956/173028108-a49aa88b-e7e4-4e26-b0a6-6bf768aa4748.png)

The Terms of use is not aligned to center.

**Solution -** 

The above problem can be solved by changing the CSS code and properly aligning the Terms of use section.

**Comment by redDwarf03** [comment]
- ok for Archethic website. (to be fixed in Archethic lab. see https://github.com/archethic-foundation/archethic-website/issues/80)
in addition, could you please:
- [ ] Change text color. We have lot of text to read in this section. The grey

 is too dark. Use a lighter color
- [ ]  Change the icon to close the terms of use window. perhaps like this icon with a cross
![Capture d’écran 2022-06-17 à 09 14 14](https://user-images.githubusercontent.com/68340133/174245743-5e9f9327-c185-4ba5-8ff3-c22c9c3bc09d.png)

- [ ] Justify the text (i'm not sure it will be good but try please)

**Comment by manujuniris** [comment]
> * [x]  ok for Archethic website. (to be fixed in Archethic lab. see [Labs page : Changes #80](https://github.com/archethic-foundation/archethic-website/issues/80))
>   in addition, could you please:
> * [x]  Change text color. We have lot of text to read in this section. The grey
> 
> is too dark. Use a lighter color
> 
> * [x]   Change the icon to close the terms of use window. perhaps like this icon with a cross
>   ![Capture d’écran 2022-06-17 à 09 14 14](https://user-images.githubusercontent.com/68340133/174245743-5e9f9327-c185-4ba5-8ff3-c22c9c3bc09d.png)
> * [x]  Justify the text (i'm not sure it will be good but try please)

All changes are done ! 
Please review http://54.39.178.165/

**Comment by redDwarf03** [comment]
ok for me
